FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN mvn -B clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/productos-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 6001
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
